# Generated by Django 3.1.4 on 2020-12-06 19:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('matrix_a', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=0), size=0)),
                ('vector_b', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=0)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=0)),
                ('e', models.FloatField(default=0.001)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
